[workspace]
resolver = "3"

members = ["client","server"]
default-members = ["client","server"]

[workspace.dependencies]
anyhow = "1.0.101"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
